apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::008089408493:role/prod-roboshop-parameter-store-eks-sa
    "helm.sh/hook": pre-install